version: "3.4"
services:
 vite_docker:
   image: node:alpine
   container_name: smskf_docker
   entrypoint: ["/srv/app/docker-start.sh"]
   ports:
     - 8000:8000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true